language: android
android:
  components:
    - build-tools-24.0.2
    - android-19
    - add-on
    - extra
    - extra-google-google_play_services
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
  - echo no | android list targets
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
